const {app,BrowserWindow}=require('electron');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const profile=fs.mkdtempSync(path.join(os.tmpdir(),'mn-capture-fixture-'));app.setPath('userData',profile);
process.on('exit',()=>fs.rmSync(profile,{recursive:true,force:true}));
const base=process.env.MN_LIBRARY_FIXTURE_URL;assert(base?.startsWith('http://127.0.0.1:'));
app.whenReady().then(async()=>{
  const win=new BrowserWindow({show:false,width:1100,height:950,webPreferences:{contextIsolation:true,backgroundThrottling:false}});
  win.webContents.on('console-message',(_event,level,message)=>{if(level>=2)console.error('Renderer:',message);});
  if(process.env.MN_FIXTURE_FOCUS)win.showInactive();
  const run=code=>win.webContents.executeJavaScript(code,true);
  const settle=()=>run('new Promise(r=>setTimeout(r,80))');
  const until=async expression=>{for(let i=0;i<100;i++){if(await run(expression))return;await new Promise(r=>setTimeout(r,30));}throw new Error(expression);};
  const click=async text=>{await run(`Array.from(document.querySelectorAll('button')).find(b=>b.textContent===${JSON.stringify(text)}).click()`);await settle();};
  const stop=async()=>{await click('■ Stop');await click('Confirm stop');};
  await win.loadURL(base);await until('document.body.innerText.includes("Recording: Synthetic app")');await settle();
  assert.equal(await run('document.querySelectorAll("[aria-label^=\\"Select SPEAKER_\\"]").length'),3,'Compact inline roster is capped');
  assert(await run('!!document.querySelector("a[href=\\"#meeting-speakers\\"]")'));
  await stop();assert.equal(await run('window.fixture.stopped'),0);assert(await run('document.body.innerText.includes("Retry Stop")'));
  await click('Restart with All system audio');await click('Stop and restart');
  assert.equal(await run('window.fixture.starts.length'),0,'Failed Stop never launches overlapping restart');
  await run('window.fixture.failStop=false');await click('Restart with All system audio');await click('Stop and restart');
  assert.equal(await run('window.fixture.starts.at(-1).groupId'),'preserved-group');
  await click('Reset live fixture');await run('window.fixture.state="recording"');await stop();
  assert.equal(await run('window.fixture.stopped'),1,'Confirmed Stop clears controls exactly once');
  await click('Reset live fixture');await run('window.fixture.state="recording";window.fixture.holdStop=true');
  await click('■ Stop');await click('Confirm stop');await click('Unmount live fixture');
  await run('window.fixture.resolveStop()');await settle();assert.equal(await run('window.fixture.stopped'),1,'Unmounted Stop never invokes stale callbacks');
  assert(await run('document.body.innerText.includes("A processing service is not ready")'));
  assert.equal(await run('document.querySelector("details pre").checkVisibility()'),false,'Raw errors remain behind disclosure');
  await click('Retry ↻');assert(await run('document.body.innerText.includes("Could not retry")'));
  await run('window.fixture.failRetry=false');await click('Retry ↻');assert.equal(await run('window.fixture.retries'),2);
  await run('Array.from(document.querySelectorAll("summary")).find(s=>s.textContent==="Technical details and retry history").click()');await settle();
  assert(await run('document.body.innerText.includes("Synthetic historical failure")'));
  if(process.env.MN_FIXTURE_RESULTS)fs.writeFileSync(path.join(process.env.MN_FIXTURE_RESULTS,'capture-recovery.png'),(await win.webContents.capturePage()).toPNG());
  console.log('CAPTURE/RECOVERY PASS Stop rejection/retry, confirmed restart/group intent, unmount fencing, plain diagnosis, bounded inline roster and technical history');win.destroy();app.quit();
}).catch(error=>{console.error(error);app.exit(1);});
