const {app,BrowserWindow} = require('electron');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path'), assert = require('node:assert/strict');
const profile = fs.mkdtempSync(path.join(os.tmpdir(),'mn-settings-fixture-')); app.setPath('userData',profile);
process.on('exit',() => fs.rmSync(profile,{recursive: true,force: true}));
const base = process.env.MN_LIBRARY_FIXTURE_URL; assert(base?.startsWith('http://127.0.0.1:'));
app.whenReady().then(async () => {
  const win = new BrowserWindow({show: false,width: 1100,height: 900,webPreferences: {contextIsolation: true,backgroundThrottling: false}});
  win.webContents.on('console-message',(_event,level,message) => {if(level>=2) console.error('Renderer:',message);});
  const run = code => win.webContents.executeJavaScript(code,true).catch(error => {throw new Error(`${code}: ${error.message}`);});
  const settle = () => run('new Promise(r => requestAnimationFrame(() => requestAnimationFrame(() => setTimeout(r,30))))');
  const until = async expression => {for(let i=0;i<100;i++){if(await run(expression))return;await new Promise(r => setTimeout(r,30));}throw new Error(expression);};
  const click = text => run(`Array.from(document.querySelectorAll('button')).find(button => button.textContent === ${JSON.stringify(text)}).click()`);
  const input = (selector,value) => run(`(() => {const input = document.querySelector(${JSON.stringify(selector)}); input.focus(); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,${JSON.stringify(value)}); input.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  await win.loadURL(base); await until('!!document.querySelector("input[type=search]")'); await settle();
  assert.equal(await run('window.fixture.captures'),0,'Opening Settings never starts capture');
  await run('Array.from(document.querySelectorAll("summary")).find(s => s.textContent.startsWith("Setup & health")).click()'); await settle();
  assert(await run('document.body.innerText.includes("Optional; does not block recording")'));
  await click('Transcription'); await settle();
  await run('Array.from(document.querySelectorAll("summary")).find(s => s.textContent === "Whisper model management").click()'); await settle();
  await run('(() => {const select = Array.from(document.querySelectorAll("select")).find(s => Array.from(s.options).some(o => o.value === "medium.en")); Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,"value").set.call(select,"small.en"); select.dispatchEvent(new Event("change",{bubbles:true}));})()'); await settle();
  await click('Use small.en'); await settle(); assert.equal(await run('window.fixture.saves.at(-1).value'),'small.en');
  await click('Test recording…'); await settle();
  await run('Array.from(document.querySelectorAll("button")).find(b => b.textContent.includes("All system audio (catch-all)")).click()'); await settle();
  assert.equal(await run('window.fixture.captures'),0,'Source selection is not capture authorization');
  await click('Cancel'); await settle(); assert.equal(await run('window.fixture.captures'),0);
  await click('Test recording…'); await settle();
  await run('Array.from(document.querySelectorAll("button")).find(b => b.textContent.includes("All system audio (catch-all)")).click()'); await settle();
  await click('Start test'); await settle(); assert.equal(await run('window.fixture.captures'),1);
  assert(await run('document.body.innerText.includes("Test audio discarded")'));
  await click('Recording'); await settle();
  assert.equal(await run('document.querySelector("[aria-label=\\"Advanced settings\\"]").hidden'),true);
  await input('input[type=search]','whisper'); await settle(); assert.equal(await run('document.querySelectorAll("[aria-label=\\"Advanced settings\\"]:not([hidden])").length'),1);
  await input('input[type=search]','zzzzunknown'); await settle(); assert(await run('document.body.innerText.includes("No matching settings")'));
  await click('Advanced'); await settle();
  const provider = value => run(`(() => {const select = Array.from(document.querySelectorAll('select')).find(s => Array.from(s.options).some(o => o.value === 'ollama')); Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value').set.call(select,${JSON.stringify(value)}); select.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  const testLlm = () => run('Array.from(document.querySelectorAll("[aria-label=\\"Advanced settings\\"] button")).find(b => b.textContent === "Test").click()');
  await provider('ollama'); await settle(); await testLlm(); await settle();
  assert.equal(await run('window.fixture.probes.at(-1)'),'http://127.0.0.1:11434');
  assert(await run('document.body.innerText.includes("not running — starts on demand")'));
  await run('window.fixture.probeCode="ENOTFOUND"'); await testLlm(); await settle();
  assert.equal(await run('document.body.innerText.includes("not running — starts on demand")'),false);
  assert(await run('document.body.innerText.includes("fetch failed")'));
  await provider('external'); await settle(); await run('window.fixture.probeCode="ECONNREFUSED"'); await testLlm(); await settle();
  assert.equal(await run('window.fixture.probes.at(-1)'),'http://localhost:1234');
  assert.equal(await run('document.body.innerText.includes("not running — starts on demand")'),false);
  await provider('lm-studio'); await settle();
  await run('(() => {const select = Array.from(document.querySelectorAll("select")).find(s => Array.from(s.options).some(o => o.value === "32768")); Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,"value").set.call(select,"16384"); select.dispatchEvent(new Event("change",{bubbles:true}));})()'); await settle();
  assert.equal(await run('window.fixture.saves.at(-1).key'),'llmContextLength');
  assert.equal(await run('window.fixture.saves.at(-1).value'),16384);
  await run('window.fixture.saves=[]');
  await click('Organization'); await settle();
  await input('input[placeholder=You]','Daniel'); await settle(); assert.equal(await run('window.fixture.saves.length'),0);
  await run('window.fixture.fail=true; document.querySelector("input[placeholder=You]").dispatchEvent(new FocusEvent("focusout",{bubbles:true}))'); await settle();
  assert(await run('document.body.innerText.includes("Couldn’t save")'));
  await run('window.fixture.fail=false'); await click('Retry'); await settle();
  assert.equal(await run('window.fixture.saves.at(-1).value'),'Daniel'); assert(await run('document.body.innerText.includes("userName: Saved")'));
  await click('Storage'); await settle(); const before = await run('window.fixture.saves.length');
  await input('[aria-label="Storage settings"] input','/fixture/new'); await settle();
  assert.equal(await run('window.fixture.saves.length'),before); await click('Apply path'); await settle();
  assert.equal(await run('window.fixture.saves.at(-1).value'),'/fixture/new'); assert(await run('document.body.innerText.includes("restarting MeetingNotes")'));
  await click('Notes & action-item history…'); await until('document.querySelector("dialog")?.open'); await settle();
  await run('document.querySelector("dialog button.w-full").click()'); await settle(); assert(await run('document.querySelector("dialog").innerText.includes("Completed original task")'));
  await click('Restore selected version'); await settle(); assert.equal(await run('window.fixture.restored'),'Old notes'); assert.equal(await run('!!document.querySelector("dialog")'),false);
  if(process.env.MN_FIXTURE_RESULTS) fs.writeFileSync(path.join(process.env.MN_FIXTURE_RESULTS,'settings.png'),(await win.webContents.capturePage()).toPNG());
  console.log('SETTINGS/HISTORY PASS section navigation/search/no matches/text blur save/failure/retry/explicit path/restart guidance/version compare/restore'); win.destroy();app.quit();
}).catch(e => {console.error(e);app.exit(1);});
