const {app,BrowserWindow} = require('electron');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path'), assert = require('node:assert/strict');
const profile = fs.mkdtempSync(path.join(os.tmpdir(),'mn-settings-fixture-')); app.setPath('userData',profile);
process.on('exit',() => fs.rmSync(profile,{recursive: true,force: true}));
const base = process.env.MN_LIBRARY_FIXTURE_URL; assert(base?.startsWith('http://127.0.0.1:'));
app.whenReady().then(async () => {
  const win = new BrowserWindow({show: false,width: 1100,height: 900,webPreferences: {contextIsolation: true,backgroundThrottling: false}});
  win.webContents.on('console-message',(_event,level,message) => {if(level>=2) console.error('Renderer:',message);});
  const run = code => win.webContents.executeJavaScript(code,true).catch(error => {throw new Error(`${code}: ${error.message}`);});
  const settle = () => run('new Promise(r => requestAnimationFrame(() => requestAnimationFrame(() => setTimeout(r,30))))');
  const until = async expression => {for(let i=0;i<100;i++){if(await run(expression))return;await new Promise(r => setTimeout(r,30));}throw new Error(expression);};
  const click = text => run(`Array.from(document.querySelectorAll('button')).find(button => button.textContent === ${JSON.stringify(text)}).click()`);
  const input = (selector,value) => run(`(() => {const input = document.querySelector(${JSON.stringify(selector)}); input.focus(); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,${JSON.stringify(value)}); input.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  await win.loadURL(base); await until('!!document.querySelector("input[type=search]")'); await settle();
  assert.equal(await run('document.querySelector("[aria-label=\\"Advanced settings\\"]").hidden'),true);
  await input('input[type=search]','whisper'); await settle(); assert.equal(await run('document.querySelectorAll("[aria-label=\\"Advanced settings\\"]:not([hidden])").length'),1);
  await input('input[type=search]','zzzzunknown'); await settle(); assert(await run('document.body.innerText.includes("No matching settings")'));
  await click('Organization'); await settle();
  await input('input[placeholder=You]','Daniel'); await settle(); assert.equal(await run('window.fixture.saves.length'),0);
  await run('window.fixture.fail=true; document.querySelector("input[placeholder=You]").dispatchEvent(new FocusEvent("focusout",{bubbles:true}))'); await settle();
  assert(await run('document.body.innerText.includes("Couldn’t save")'));
  await run('window.fixture.fail=false'); await click('Retry'); await settle();
  assert.equal(await run('window.fixture.saves.at(-1).value'),'Daniel'); assert(await run('document.body.innerText.includes("userName: Saved")'));
  await click('Storage'); await settle(); const before = await run('window.fixture.saves.length');
  await input('[aria-label="Storage settings"] input','/fixture/new'); await settle();
  assert.equal(await run('window.fixture.saves.length'),before); await click('Apply path'); await settle();
  assert.equal(await run('window.fixture.saves.at(-1).value'),'/fixture/new'); assert(await run('document.body.innerText.includes("restarting MeetingNotes")'));
  await click('Notes & action-item history…'); await until('document.querySelector("dialog")?.open'); await settle();
  await run('document.querySelector("dialog button.w-full").click()'); await settle(); assert(await run('document.querySelector("dialog").innerText.includes("Completed original task")'));
  await click('Restore selected version'); await settle(); assert.equal(await run('window.fixture.restored'),'Old notes'); assert.equal(await run('!!document.querySelector("dialog")'),false);
  if(process.env.MN_FIXTURE_RESULTS) fs.writeFileSync(path.join(process.env.MN_FIXTURE_RESULTS,'settings.png'),(await win.webContents.capturePage()).toPNG());
  console.log('SETTINGS/HISTORY PASS section navigation/search/no matches/text blur save/failure/retry/explicit path/restart guidance/version compare/restore'); win.destroy();app.quit();
}).catch(e => {console.error(e);app.exit(1);});
