const { app, BrowserWindow } = require('electron');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'meetingnotes-obsidian-ui-'));
app.setPath('userData', profile);
const timeout = setTimeout(() => app.exit(1), 60000);
app.whenReady().then(async () => {
  const win = new BrowserWindow({ show: false, width: 1000, height: 760, webPreferences: { contextIsolation: true, nodeIntegration: false, backgroundThrottling: false } });
  const run = code => win.webContents.executeJavaScript(code, true);
  const until = async code => { for (let i = 0; i < 150; i++) { if (await run(code)) return; await new Promise(r => setTimeout(r, 30)); } throw Error(`Not ready: ${code}`); };
  const click = async text => { await run(`Array.from(document.querySelectorAll('button')).find(b => b.textContent === ${JSON.stringify(text)}).click()`); await new Promise(r => setTimeout(r, 60)); };
  await win.loadURL(process.env.MN_OBSIDIAN_FIXTURE_URL);
  await until(`!!document.querySelector('button')`);
  assert(await run(`document.querySelector('section').getBoundingClientRect().height < 180`));
  await click('Configure…');
  await until(`document.querySelector('dialog').open`);
  await click('Choose…');
  await click('Preview sync');
  assert.deepEqual(await run('window.fixture.calls'), ['preview']);
  assert(await run(`document.querySelector('dialog').textContent.includes('500 completed meetings')`));
  await click('Enable and sync');
  await click('Close');
  assert(await run(`document.activeElement.textContent === 'Configure…'`));
  await click('Configure…');
  await click('Preview sync');
  assert.equal(await run(`document.querySelector('[role="alert"]')?.textContent ?? ''`), '');
  await run('window.fixture.issues()');
  await click('Sync now / retry');
  assert.equal(await run(`document.querySelectorAll('[aria-label="Sync issues"] > div').length`), 100);
  assert(await run(`document.querySelector('dialog').getBoundingClientRect().height <= innerHeight - 30`));
  await run('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))');
  fs.writeFileSync(path.join(profile, 'configured.png'), (await win.webContents.capturePage()).toPNG());
  await click('Review note');
  await click('Replace generated content…');
  assert(!(await run('window.fixture.calls.includes("replace")')));
  await click('Cancel');
  await click('Replace generated content…');
  await click('Back up and replace generated content');
  assert(await run('window.fixture.calls.includes("replace")'));
  await click('Recreate views…');
  assert(!(await run('window.fixture.calls.includes("repair")')));
  await click('Back up and recreate views');
  await click('Turn off automatic sync');
  await click('Close');
  assert(await run(`document.querySelector('section').textContent.includes('Automatic sync is off')`));
  win.setContentSize(440, 620);
  await click('Configure…');
  assert(await run(`document.querySelector('dialog').getBoundingClientRect().width <= innerWidth`));
  fs.writeFileSync(path.join(profile, 'narrow.png'), (await win.webContents.capturePage()).toPNG());
  console.log('Obsidian UI fixture passed: preview/enable, reconfigure, 100 issues, bounded layout, conflict/repair confirmations, disable, focus restoration. Screenshots:', profile);
  clearTimeout(timeout); win.destroy(); app.quit();
}).catch(error => { console.error(error); clearTimeout(timeout); app.exit(1); });
